# Generated by Django 4.0.5 on 2022-08-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcourse', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('hour', models.DateTimeField()),
                ('state', models.BooleanField(default='null')),
            ],
        ),
    ]
